[build]
  # This command is correct.
  command = "pip install -r requirements.txt"
  # This line tells Netlify that any python files it finds should be treated as functions.
  # This is the line that was missing.
  functions = "."

[functions]
  # This is also correct, it includes your template/static files.
  included_files = ["templates/**", "static/**"]

# This redirect is correct, but was pointing to a function that wasn't being built.
# Now that the function will be built, this will work.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
