# This is the command to install your Python packages.
[build]
  command = "pip install -r requirements.txt"

# This section tells Netlify to treat your main.py as a "serverless function".
[functions]
  # This makes sure your templates and static folders are available.
  included_files = ["templates/**", "static/**"]

# THIS IS THE CRITICAL PART
# It tells Netlify to send all traffic to your Python function.
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main" # "main" MUST match your python filename
  status = 200
